"""restore_missing_columns

Revision ID: 1efbd166ed12
Revises: a1b2c3d4e5f6
Create Date: 2026-02-18 18:31:02.198316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1efbd166ed12'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # DUPLICATE: handled in g1h2i3j4k5l6
    # op.add_column('chat_sessions', sa.Column('news_id', sa.Integer(), nullable=True))
    # op.create_index(op.f('ix_chat_sessions_news_id'), 'chat_sessions', ['news_id'], unique=False)
    # op.create_foreign_key(None, 'chat_sessions', 'news_items', ['news_id'], ['id'])
    op.drop_index('ix_llm_audit_created_at', table_name='llm_audit')
    op.drop_index('news_items_embedding_idx', table_name='news_items', postgresql_using='hnsw')
    # DUPLICATE: handled in g1h2i3j4k5l6
    # op.add_column('news_settings', sa.Column('news_chat_prompt', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))
    op.alter_column('news_settings', 'harvester_nightly_prompt',
               existing_type=sa.VARCHAR(),
               server_default='', nullable=False)
    op.alter_column('news_settings', 'harvester_search_prompt',
               existing_type=sa.VARCHAR(),
               server_default='', nullable=False)
    op.alter_column('news_settings', 'allowed_tags',
               existing_type=sa.VARCHAR(),
               server_default='', nullable=False)
    op.drop_index('ix_webinar_chunks_embedding', table_name='webinar_chunks', postgresql_using='hnsw')
    op.drop_column('webinar_schedules', 'is_sprint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webinar_schedules', sa.Column('is_sprint', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index('ix_webinar_chunks_embedding', 'webinar_chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.alter_column('news_settings', 'allowed_tags',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('news_settings', 'harvester_search_prompt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('news_settings', 'harvester_nightly_prompt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('news_settings', 'news_chat_prompt')
    op.create_index('news_items_embedding_idx', 'news_items', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index('ix_llm_audit_created_at', 'llm_audit', ['created_at'], unique=False)
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_news_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'news_id')
    # ### end Alembic commands ###
