"""add_program_and_is_sprint

Revision ID: 722f23e1b5a9
Revises: 6e22590f8811
Create Date: 2026-02-11 20:18:55.823134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722f23e1b5a9'
down_revision: Union[str, Sequence[str], None] = '6e22590f8811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webinar_schedules', sa.Column('is_sprint', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('webinar_schedules', sa.Column('program', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webinar_schedules', 'program')
    op.drop_column('webinar_schedules', 'is_sprint')
    # ### end Alembic commands ###
