"""Add ForYou feed tables and settings

Revision ID: 7301ca4ee813
Revises: l6m7n8o9p0q1
Create Date: 2026-02-25 19:42:22.282624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7301ca4ee813'
down_revision: Union[str, Sequence[str], None] = 'l6m7n8o9p0q1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_news_feed_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_ids', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_news_feed_cache_user_id'), 'user_news_feed_cache', ['user_id'], unique=True)
    op.create_table('user_viewed_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'news_id', name='uq_user_viewed_news')
    )
    op.create_index(op.f('ix_user_viewed_news_news_id'), 'user_viewed_news', ['news_id'], unique=False)
    op.create_index(op.f('ix_user_viewed_news_user_id'), 'user_viewed_news', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_viewed_news_viewed_at'), 'user_viewed_news', ['viewed_at'], unique=False)
    op.add_column('news_settings', sa.Column('foryou_enabled', sa.Boolean(), nullable=False))
    op.add_column('news_settings', sa.Column('foryou_days_limit', sa.Integer(), nullable=False))
    op.add_column('news_settings', sa.Column('foryou_vector_limit', sa.Integer(), nullable=False))
    op.add_column('news_settings', sa.Column('foryou_rerank_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('news_settings', 'news_chat_prompt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_webinar_libraries_search_embedding', table_name='webinar_libraries', postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_webinar_libraries_search_embedding', 'webinar_libraries', ['search_embedding'], unique=False, postgresql_using='hnsw')
    op.alter_column('news_settings', 'news_chat_prompt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('news_settings', 'foryou_rerank_prompt')
    op.drop_column('news_settings', 'foryou_vector_limit')
    op.drop_column('news_settings', 'foryou_days_limit')
    op.drop_column('news_settings', 'foryou_enabled')
    op.drop_index(op.f('ix_user_viewed_news_viewed_at'), table_name='user_viewed_news')
    op.drop_index(op.f('ix_user_viewed_news_user_id'), table_name='user_viewed_news')
    op.drop_index(op.f('ix_user_viewed_news_news_id'), table_name='user_viewed_news')
    op.drop_table('user_viewed_news')
    op.drop_index(op.f('ix_user_news_feed_cache_user_id'), table_name='user_news_feed_cache')
    op.drop_table('user_news_feed_cache')
    # ### end Alembic commands ###
