"""add_news_items

Revision ID: d86d05bb73d7
Revises: 833f24f2b6b0
Create Date: 2026-02-17 14:02:21.615067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd86d05bb73d7'
down_revision: Union[str, Sequence[str], None] = '833f24f2b6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_urls', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='newsstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_llm_audit_created_at', table_name='llm_audit')
    op.drop_index('ix_webinar_chunks_embedding', table_name='webinar_chunks', postgresql_using='hnsw')
    op.drop_column('webinar_schedules', 'is_sprint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webinar_schedules', sa.Column('is_sprint', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index('ix_webinar_chunks_embedding', 'webinar_chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index('ix_llm_audit_created_at', 'llm_audit', ['created_at'], unique=False)
    op.drop_table('news_items')
    # ### end Alembic commands ###
